"""Python bindings to GGPO"""
from __future__ import annotations
import ggpo_py
import typing

__all__ = [
    "GGPOSession"
]


class GGPOSession():
    def __init__(self, game_title: str, port: int, n_players: int, game_status: object) -> None: ...
    def add_local_input(self, arg0: object, arg1: int) -> object: ...
    def add_player(self, arg0: int, arg1: object) -> object: ...
    def advance_frame(self) -> object: ...
    def cbk_advance_frame(self, arg0: function) -> None: ...
    def cbk_log_game_state(self, arg0: function) -> None: ...
    def cbk_on_event(self, arg0: function) -> None: ...
    def disconnect_player(self, arg0: object) -> object: ...
    def idle(self, arg0: int) -> object: ...
    def set_disconnect_notify_start(self, arg0: int) -> object: ...
    def set_disconnect_timeout(self, arg0: int) -> object: ...
    def set_frame_delay(self, arg0: object, arg1: int) -> object: ...
    def start(self) -> object: ...
    def stop(self) -> object: ...
    pass
