"""Python bindings to GGPO"""
from __future__ import annotations
from typing import Callable

import ggpo_py.ggpo_py
import typing

__all__ = [
    "GGPOSession"
]


class GGPOSession:
    def __init__(self, game_title: str, port: int, n_players: int, game_status: object) -> None: ...
    def add_local_input(self, player: object, input: int) -> object: ...
    def add_player(self, player: object) -> object: ...
    def advance_frame(self) -> object: ...
    def cbk_advance_frame(self, callback: Callable) -> None: ...
    def cbk_log_game_state(self, callback: Callable) -> None: ...
    def cbk_on_event(self, callback: Callable) -> None: ...
    def cbk_on_rollback(self, callback: Callable) -> None: ...
    def disconnect_player(self, player: object) -> object: ...
    def idle(self, time_ms: int) -> object: ...
    def set_disconnect_notify_start(self, time_ms: int) -> object: ...
    def set_disconnect_timeout(self, time_ms: int) -> object: ...
    def set_frame_delay(self, player: object, time_ms: int) -> object: ...
    def start(self) -> object: ...
    def stop(self) -> object: ...
    def synchronize_input(self) -> tuple: ...
    pass
